import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/app/[lang]/components/Header";
import Footer from "@/app/[lang]/components/Footer";
import { montserrat, openSans, rubik } from "./fonts";
import { i18n, type Locale } from "@/i18n-config";
import LocaleSwitcher from "./components/LocaleSwitcher";
import { getDictionary } from "@/get-dictionary";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}
export const metadata: Metadata = {
  title: "Envent",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  const dictionary = await getDictionary(params.lang);
  return (
    <html lang={params.lang}>
      <body
        className={`${rubik.variable} ${openSans.variable} ${montserrat.variable}`}
      >
        <Header d={dictionary.header.topList} />
        <LocaleSwitcher />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
